### ISSUE TITLE
App closes when you press on settings icon 

### ISSUE THREAD

**Issue by OlivierJM** [Adventech/sabbath-school-ios#135] opened 2023-06-17 20:59 UTC
Not sure if this is worth reporting since it is currently happening on IOS 17(beta) and maybe related to that

 but when you press on settings icon the app automatically closes. I am attaching a screen recording and a screenshot. 

![IMG_6504](https://github.com/Adventech/sabbath-school-ios/assets/11255454/da92a0cf-de32-416a-a297-4181d24f2e5b)

https://github.com/Adventech/sabbath-school-ios/assets/11255454/b9c9d7a6-b4a5-4bb1-97be-5979f6a99df9

**Comment by VitalikL** [comment] 2023-06-18 16:48
@EmersonCarpes Looks like a real crash associated with the Settings menu.

**Comment by VitalikL** [comment] 2023-10-16 22:35
@EmersonCarpes I can confirm its still happening with the latest prod version. Lots of people can't sign out

**Comment by VitalikL** [comment] 2024-12-10 14:34
@OlivierJM Fixed in the upcoming release

**Closed as completed by VitalikL** 2024-12-10 14:34 UTC
